### ISSUE TITLE
[App] Input channels list in preferences is wrong

### ISSUE THREAD

**Issue by splisp** [sdatkinson/NeuralAmpModelerPlugin#368]
In the Preferences dialog, the list of input channels is always populated for the first listed device, and not for the actually selected device.  In the following screenshots, we can see 16 channels but my ZED1 10 only has 4:

![1](https://github.com/sdatkinson/NeuralAmpModelerPlugin/assets/2437263/6afd7cb9-99d6-47a1-b180-7325954e8bda)

This is because we are seeing the list of input channels for the ReaRoute device, the first one in the list:

![2](https://github.com/sdatkinson/NeuralAmpModelerPlugin/assets/2437263/d27d9a91-ccbd-4afa-b5d8-c0014cd46e39)

I have verified in the debug that, in IPlugAPPHost::PopulateDriverSpecificControls(), mState.mAudioInDev.Get() always returns "ReaRoute ASIO (x64)" and I have found no way to change it (applying the dialog, closing it, doesn't help).

I am on Windows 10 professional 64 bit, running the standalone app, built from sources in debug mode (just forked).

**Comment by splisp** [comment]
I understand that the file IPlugAPP_dialog.cpp is not in NeuralAmpModeler's sources, but in iPlug. May I tag @olilarkin ...

**Comment by olilarkin** [comment]
Thanks, will address this

**Comment by splisp** [comment]
In the current version of the app this bug seems to not be present anymore. I don't know if Oli made something to fix it or if it's a coincidence (I quickly searched through the latest iPlug's commits but I couldn't spot something related to this)

**Comment by olilarkin** [comment]
Unfortunately there are still problems with the iPlug2 App wrapper... will get around to fixing it up sometime!

**Comment by sdatkinson** [comment]
Looks resolved with #621 :)

https://github.com/user-attachments/assets/59be5418-e2ea-4018-89eb-d6d75defce57

**Comment by splisp** [comment]
Actually there is still some problem with this issue.  I have just rebuilt from sources, and when `IPlugAPPHost::PopulateAudioInputList()` is called it still receives the first ASIO device (in my case, ReaRoute) and not the currently selected one.  The result is that the comboboxes "Input1 (L)" and "Input 2 (R)" always list 16 channels, while the selected device has only 4.  On the contrary, `IPlugAPPHost::PopulateAudioOutputList()` receives the correct device.

In IPlugAPP_dialog.cpp at line 202, indevidx is 0 (wrong) while outdevidx is 4 (correct).  The Input Device combo on the dialog is disabled so the user cannot actually select an input device, anyway it shows the correct device (it follows the output device the user selects). 

@olilarkin I'm going to submit a patch to iPlug2 to fix this

**Comment by splisp** [comment]
> Looks resolved with [#621](https://github.com/sdatkinson/NeuralAmpModelerPlugin/pull/621) :)
> 
>  Screen.Recording.2026-05-03.at.12.42.21.PM.mov

The problem in fact didn't happen on Mac, only on Windows

**Comment by splisp** [comment]
> Looks resolved with [#621](https://github.com/sdatkinson/NeuralAmpModelerPlugin/pull/621) :)
> 
>  Screen.Recording.2026-05-03.at.12.42.21.PM.mov

The problem in fact didn't happen on Mac, only on Windows
